name: Build & deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install NPM packages
        run: npm install
        working-directory: ./frontend

      - name: Check for code format
        run: npm run lint
        working-directory: ./frontend

      - name: Build project
        run: npm run build
        env:
          REACT_APP_OPEN_WEATHER_CITY_IDS: 2885657,3214104
          REACT_APP_ROOMS: living_room,core
          REACT_APP_MODE: demo
        working-directory: ./frontend

      - name: Upload build files
        uses: actions/upload-artifact@v2
        with:
          name: production
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production
          path: ./build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
